### ISSUE TITLE
Rockefeller logo breaking on mobile

### ISSUE THREAD

**Issue by Deepthi-Chand** [CivicDataLab/IDS-DRR-Frontend#50]

**Comment by aparnasr1** [comment]
Please use the white RF logo since it's a dark BG. We got approvals for the white RF logo.

(you'll find the PNG from the Figma [desktop](https://www.figma.com/design/cvt8ZwCF0C1Z4788NtZO8h/AD-%3A-Version-3?node-id=2500-1161) & [mobile](https://www.figma.com/design/Yx2asiOvaNeVcy4p5Kaabc/IDS-DRR-Mobile-(Responsive)?node-id=0-1) screen)
